MyBlogs/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView, RedirectView
from django.views.static import serve

from MyBlogs.settings import MEDIA_ROOT

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html', content_type='text/html')),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    path('admin/', admin.site.urls),
    path('blog/', include('blogs.urls')),
    path('captcha/', include('captcha.urls')),  # 图片验证码路由
    path('user/', include('users.urls')),
    path('user/', include('users.urls.password_url')),
    path("media/<path:path>", serve, {"document_root": MEDIA_ROOT}),

    re_path(r'^api/(?P<version>v\d+)/', include("MyBlogs.urls_api")),
]

blogs/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blogs'
urlpatterns = [
    path('<int:user_id>/', views.author, name='author'),
    path('<int:user_id>/<int:blog_id>.html', views.detail, name='detail'),
    path('create_blog', views.blog_create, name='blog_create'),

    # tag(标签)的增删改查
    path('tagCreate/<str:name>', views.tag_create, name='tag_create'),
    path('tagDelete/<int:tag_id>', views.tag_delete, name='tag_delete'),
    path('tagUpdate/<int:tag_id>/<str:name>', views.tag_update, name='tag_update'),
    path('tagIsExist/<str:name>', views.tag_is_exist, name='tag_is_exist'),

    # API
    path('list', views.BlogsView.as_view()),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('join', views.user_join, name='join'),
    path('update', views.user_update, name='update'),
    path('password', views.user_password, name='password'),
    path('isExist', views.user_is_exist, name='isExist'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-Hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
    <script src="{% static 'jquery/3.3.1/jquery.min.js' %}"></script>
    <title>{% block title %}{% endblock title %}</title>
    {% block style %}{% endblock style %}
    {% block link %}{% endblock link %}
    {% block script %}{% endblock script %}

    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <div class="layui-header">
        <div class="layui-logo">layui 后台布局</div>
        <!-- 头部区域（可配合layui已有的水平导航） -->
        <ul class="layui-nav layui-layout-left">
            <li class="layui-nav-item"><a href="">控制台</a></li>
            <li class="layui-nav-item"><a href="">商品管理</a></li>
            <li class="layui-nav-item"><a href="">用户</a></li>
            <li class="layui-nav-item">
                <a href="javascript:">其它系统</a>
                <dl class="layui-nav-child">
                    <dd><a href="">邮件管理</a></dd>
                    <dd><a href="">消息管理</a></dd>
                    <dd><a href="">授权管理</a></dd>
                </dl>
            </li>
        </ul>
        <ul class="layui-nav layui-layout-right">
            {% if request.user.is_authenticated %}
                <li class="layui-nav-item">
                    <a href="javascript:">
                        <img src="http://t.cn/RCzsdCq" class="layui-nav-img" alt="">
                        {% if request.user.userinfo %}
                            {{ request.user.userinfo.nickname }}
                        {% else %}
                            {{ request.user }}
                        {% endif %}
                    </a>
                    <dl class="layui-nav-child">
                        <dd><a href="">基本资料</a></dd>
                        <dd><a href="{% url 'users:update' %}">安全设置</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item"><a href="{% url 'users:logout' %}">退了</a></li>

            {% else %}
                <li class="layui-nav-item"><a href="{% url 'users:login' %}">登录</a></li>
                <li class="layui-nav-item"><a href="{% url 'users:join' %}">注册</a></li>
            {% endif %}
        </ul>
    </div>

    <div class="layui-side layui-bg-black">
        <div class="layui-side-scroll">
            <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
            <ul class="layui-nav layui-nav-tree" lay-filter="test">
                <li class="layui-nav-item layui-nav-itemed">
                    <a class="" href="javascript:">所有商品</a>
                    <dl class="layui-nav-child">
                        <dd><a href="javascript:">列表一</a></dd>
                        <dd><a href="javascript:">列表二</a></dd>
                        <dd><a href="javascript:">列表三</a></dd>
                        <dd><a href="">超链接</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item">
                    <a href="javascript:">解决方案</a>
                    <dl class="layui-nav-child">
                        <dd><a href="javascript:">列表一</a></dd>
                        <dd><a href="javascript:">列表二</a></dd>
                        <dd><a href="">超链接</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item"><a href="">云市场</a></li>
                <li class="layui-nav-item"><a href="">发布商品</a></li>
            </ul>
        </div>
    </div>

    <div class="layui-body layui-tab">
        <div class="layui-tab-content">
            <!-- 内容主体区域 -->
            <div style="padding: 15px;">内容主体区域</div>
        </div>
        {% block content %}{% endblock content %}
    </div>
</div>
<script src="{% static 'layui/layui.js' %}"></script>
<script>
    let element;
    layui.use('element', function () {
        element = layui.element;
        element.init();
    });
</script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}首页{% endblock title %}
{% block content %}
    <div class="layui-tab-content">
        <!-- 内容主体区域 -->
        <div style="padding: 15px;">内容主体区域</div>
        <a href="{% url 'blogs:blog_create' %}">写博客</a>
    </div>
{% endblock content %}