MyBlogs/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView, RedirectView
from django.views.static import serve

from MyBlogs.settings import MEDIA_ROOT

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html', content_type='text/html')),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    path('admin/', admin.site.urls),
    path('blog/', include('blogs.urls')),
    path('captcha/', include('captcha.urls')),  # 图片验证码路由
    path('user/', include('users.urls')),
    path('user/', include('users.urls.password_url')),
    path("media/<path:path>", serve, {"document_root": MEDIA_ROOT}),

    re_path(r'^api/(?P<version>v\d+)/', include("MyBlogs.urls_api")),
]

blogs/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blogs'
urlpatterns = [
    path('<int:user_id>/', views.author, name='author'),
    path('<int:user_id>/<int:blog_id>.html', views.detail, name='detail'),
    path('create_blog', views.blog_create, name='blog_create'),

    # tag(标签)的增删改查
    path('tagCreate/<str:name>', views.tag_create, name='tag_create'),
    path('tagDelete/<int:tag_id>', views.tag_delete, name='tag_delete'),
    path('tagUpdate/<int:tag_id>/<str:name>', views.tag_update, name='tag_update'),
    path('tagIsExist/<str:name>', views.tag_is_exist, name='tag_is_exist'),

    # API
    path('list', views.BlogsView.as_view()),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('join', views.user_join, name='join'),
    path('update', views.user_update, name='update'),
    path('password', views.user_password, name='password'),
    path('isExist', views.user_is_exist, name='isExist'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User


class UserInfo(models.Model):
    choices = (
        (True, '男'),
        (False, '女'),
    )
    user = models.OneToOneField(to=User, on_delete=models.CASCADE, verbose_name='用户')
    nickname = models.CharField(max_length=20, default='新用户', verbose_name='昵称')
    gender = models.BooleanField(choices=choices, default=True, verbose_name='性别')

    def __str__(self):
        return "%s : %s" % (self.user, self.nickname)

    class Meta:
        db_table = 't_userInfo'
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

users/views.py
from captcha.helpers import captcha_image_url
from captcha.models import CaptchaStore
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import TemplateView
from rest_framework.response import Response
from rest_framework.views import APIView

from users.models import UserInfo
from users.utils import get_or_create_author_group, user_perm_init


class UserLoginView(TemplateView):
    """用户登录视图"""
    template_name = 'users/login.html'

    def get(self, request, *args, **kwargs):
        next_url = request.GET.get('next', '/')

        if request.user.is_authenticated:
            """若用户已登录，则跳过登录界面"""
            return redirect(next_url)

        captcha_hashkey = CaptchaStore.generate_key()  # 生成验证码的hashkey
        captcha_img_url = captcha_image_url(captcha_hashkey)  # 生成验证码图片
        self.extra_context = {
            'captcha_hashkey': captcha_hashkey,
            'captcha_img_url': captcha_img_url,
            'next': next_url,
        }
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        next_url = self.request.GET.get('next') or self.request.POST.get('next', '/')
        username = request.POST.get('username').strip()
        password = request.POST.get('password').strip()
        hashkey = request.POST.get('captcha_0')
        captcha = request.POST.get('captcha_1').strip()

        data = {
            'code': -1,
            'msg': 'error',
            'next': next_url,
        }

        captcha_store = CaptchaStore.objects.filter(hashkey=hashkey).first()
        if not captcha_store or captcha_store.response != captcha.lower():
            data['msg'] = '验证码错误'
            return JsonResponse(data)

        if not username or not password:
            data['msg'] = '用户名或密码不能为空'
            return JsonResponse(data)

        user = auth.authenticate(username=username, password=password)
        if not user:
            data['msg'] = '用户名或密码错误'
            return JsonResponse(data)

        auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        data['code'] = 200
        data['msg'] = "登录成功"
        return JsonResponse(data)


class UserJoinView(TemplateView):
    """用户注册视图"""
    template_name = 'users/join.html'

    def get(self, request, *args, **kwargs):
        next_url = request.GET.get('next', '/')
        if request.user.is_authenticated:
            """若用户已登录，则跳过注册界面"""
            return redirect(next_url)

        captcha_hashkey = CaptchaStore.generate_key()
        captcha_img_url = captcha_image_url(captcha_hashkey)
        self.extra_context = {
            'captcha_hashkey': captcha_hashkey,
            'captcha_img_url': captcha_img_url,
            'next': next_url,
        }
        return super(UserJoinView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        next_url = self.request.GET.get('next') or self.request.POST.get('next', '/')
        username = request.POST.get('username').strip()
        password = request.POST.get('password').strip()
        hashkey = request.POST.get('captcha_0', 'error')
        captcha = request.POST.get('captcha_1', 'error_1').strip()
        nickname = request.POST.get('nickname', '新用户')
        gender = request.POST.get('gender')

        data = {
            'code': -1,
            'next': next_url,
            'msg': 'error',
        }

        captcha_store = CaptchaStore.objects.filter(hashkey=hashkey).first()
        if not captcha_store or captcha_store.response != captcha.lower():
            data['msg'] = '验证码错误'
            return JsonResponse(data=data)

        if not username or not password:
            data['msg'] = '用户名或密码不能为空'
            return JsonResponse(data)

        if User.objects.filter(username=username).exists():
            data['msg'] = '该用户名已存在'
            return JsonResponse(data)

        user = User.objects.create_user(username=username, password=password)
        group = get_or_create_author_group()
        user.groups.add(group)
        user_info = UserInfo.objects.create(user=user)
        user_perm_init(user)
        if nickname:
            user_info.nickname = nickname.strip()
        if gender is not None:
            user_info.gender = bool(int(gender))
        user_info.save()
        auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        data['code'] = 200
        data['msg'] = "注册成功"
        return JsonResponse(data)


class UserIsExistView(APIView):
    """ 查询用户是否已存在 """

    def get(self, *args, **kwargs):
        username = self.request.query_params.get('username')
        data = {
            'code': 200,
            'isExist': False,
            'username': username,
        }
        if username:
            data['isExist'] = User.objects.filter(username=username).exists()
        return Response(data)


@login_required
def user_logout(request):
    """ 退出登录 """
    auth.logout(request)
    return redirect("users:login")


@login_required
def user_update(request) -> (HttpResponse, JsonResponse):
    """TODO 修改用户信息"""
    if request.method == "GET":
        return render(request, "users/update.html")

    if request.method == "POST":
        user = request.user
        data = {
            'code': -1,
            'msg': 'error',
            'username': user.username
        }

        if request.is_ajax() or True:  # FIXME 测试 需要删掉 ` or True`
            nickname = request.POST.get('nickname')
            gender = request.POST.get('gender')
            if nickname:
                user.userinfo.nickname = nickname
            if gender is not None:
                user.userinfo.gender = bool(int(gender))
            user.userinfo.save()
            data['code'] = 200
            data['msg'] = '修改成功'
            data['next'] = reverse("users:update")
            return JsonResponse(data=data)

    return HttpResponse("403 禁止访问", status=403)


@login_required
def user_password(request) -> (HttpResponse, JsonResponse):
    """
    修改用户密码
    只接受Ajax的POST请求
    """
    if request.method == "GET":
        return redirect('users:update')
    user = request.user
    if request.method == "POST" and user.has_perm('change_user', user):
        if request.is_ajax() or True:  # FIXME 测试 需要删掉 ` or True`
            data = {
                'code': -1,
                'msg': 'error',
                'username': user.username,
            }
            old_password = request.POST.get('old_password')
            new_password = request.POST.get('new_password')

            if old_password and new_password:
                if not user.check_password(old_password):
                    data['msg'] = '密码错误'
                    return JsonResponse(data=data)

                user.set_password(new_password)
                user.save()
                data['code'] = 200
                data['msg'] = '密码修改成功，请重新登录'
                data['next'] = reverse('users:login')
            return JsonResponse(data=data)

    return HttpResponse("403 禁止访问", status=403)

templates/users/join.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-Hans">
<head>
    <meta charset="UTF-8">
    <title>注册新用户</title>
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
    <script src="{% static 'jquery/3.3.1/jquery.min.js' %}"></script>
    <script src="{% static 'layui/layui.js' %}"></script>
</head>
<body>
<div style="margin: 10px auto; width: max-content">
    <form method="post" action="{% url 'users:join' %}" class="layui-form" style="margin-top: 20px">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <div class="layui-form-item">
            <label class="layui-form-label" for="id_username">用户ID：</label>
            <div class="layui-input-inline">
                <input type="text" name="username" id="id_username" maxlength="10" required
                       lay-verify="required|isExist"
                       placeholder="请输入用户ID"
                       autocomplete="off" class="layui-input">
            </div>
            <div class="layui-form-mid layui-word-aux">&nbsp;</div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" for="id_nickname">昵称：</label>
            <div class="layui-input-inline">
                <input type="text" name="nickname" id="id_nickname" maxlength="15" required lay-verify="required"
                       placeholder="请输入昵称"
                       autocomplete="off" class="layui-input">
            </div>
            <div class="layui-form-mid layui-word-aux">&nbsp;</div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" for="password">设置密码：</label>
            <div class="layui-input-inline">
                <input type="password" name="password" maxlength="15" required lay-verify="required|pass"
                       placeholder="请输入密码" lay-type="pass"
                       autocomplete="off" class="layui-input" id="password">
            </div>
            <div class="layui-form-mid layui-word-aux">&nbsp;</div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" for="password_1">确认密码：</label>
            <div class="layui-input-inline">
                <input type="password" maxlength="15" required lay-verify="required|confirmPass"
                       placeholder="请确认密码"
                       autocomplete="off" class="layui-input" id="password_1">
            </div>
            <div class="layui-form-mid layui-word-aux">&nbsp;</div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">性别：</label>
            <div class="layui-input-block">
                <label>
                    <input type="radio" name="gender" value=1 title="男" checked>
                </label>
                <label>
                    <input type="radio" name="gender" value=0 title="女">
                </label>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" for="captcha_1">验证码：</label>
            <div class="layui-input-inline">
                <input id="captcha_0" name="captcha_0" type="hidden" value="{{ captcha_hashkey }}"/>
                <input type="text" name="captcha_1" maxlength="20" required lay-verify="required"
                       placeholder="请输入验证码" spellcheck="false" autocapitalize="off" autocorrect="off"
                       autocomplete="off" class="layui-input" id="captcha_1">
            </div>
            <div class="layui-form-mid" style="padding: 0 !important;">
                <a href="javascript:" title="点击一下刷新验证码"><img src="{{ captcha_img_url }}" alt="验证码" class="captcha"/></a>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-input-block">
                <button class="layui-btn" lay-submit lay-filter="formSubmit">注&nbsp;册</button>
                <button type="reset" class="layui-btn layui-btn-primary">重&nbsp;置</button>
            </div>
        </div>

    </form>
    去<a href="{% url 'users:login' %}">登录</a>
</div>

<script src="{% static 'js/ajax_csrf.js' %}"></script>

<script>
    let element, layer, form;
    layui.use(['element', 'layer', 'form',], function () {
        element = layui.element;
        element.init();
        layer = layui.layer;
        form = layui.form;
        form.on('submit(formSubmit)', function (data) {
            $.ajax({
                url: data.form.action,
                type: "post",
                data: data.field,
                success: function (data) {
                    if (data["code"] === 200) {
                        layer.msg(data["msg"]);
                        setTimeout(function () {
                            window.location = data["next"];
                        }, 2 * 1000);
                    } else {
                        layer.msg(data["msg"]);
                        $.getJSON("{% url 'captcha-refresh' %}", function (result) {
                            $('.captcha').attr('src', result['image_url']);
                            $('#captcha_0').val(result['key'])
                        });
                    }
                }
            });
            return false;
        });

        form.verify({
            pass: [/(.+){6,15}$/, '密码必须6到15位'],
            confirmPass: function (value) {
                if ($('input[name=password]').val() !== value)
                    return '两次密码输入不一致！';
            },
            isExist: function (value) {
                let data = false;
                $.ajax({
                    url: "{% url 'users:isExist' %}",
                    contentType: "application/json",
                    dataType: 'json',
                    type: "get",
                    async: false,
                    data: {"username": value},
                    success: function (result) {
                        data = result['isExist'];
                    },
                });
                if (data) {
                    return '该用户ID已存在';
                }
            }
        });
    });
    $('.captcha').click(function () {
        $.getJSON("{% url 'captcha-refresh' %}", function (result) {
            $('.captcha').attr('src', result['image_url']);
            $('#captcha_0').val(result['key'])
        });
    });
</script>
</body>
</html>

templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-Hans">
<head>
    <meta charset="UTF-8">
    <title>用户登录</title>
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
    <script src="{% static 'jquery/3.3.1/jquery.min.js' %}"></script>
    <script src="{% static 'layui/layui.js' %}"></script>
</head>
<body>
<div style="margin: 10px auto; width: max-content">
    <form method="post" action="" class="layui-form" style="margin-top: 20px">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <div class="layui-form-item">
            <label class="layui-form-label" for="id_username">用户ID：</label>
            <div class="layui-input-inline">
                <input type="text" name="username" id="id_username" maxlength="10" required lay-verify="required"
                       placeholder="请输入用户ID"
                       autocomplete="off" class="layui-input">
            </div>
            <div class="layui-form-mid layui-word-aux">&nbsp;</div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" for="password">密码：</label>
            <div class="layui-input-inline">
                <input type="password" name="password" maxlength="15" required lay-verify="required"
                       placeholder="请输入密码"
                       autocomplete="off" class="layui-input" id="password">
            </div>
            <div class="layui-form-mid layui-word-aux">&nbsp;</div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" for="captcha_1">验证码：</label>
            <div class="layui-input-inline">
                <input id="captcha_0" name="captcha_0" type="hidden" value="{{ captcha_hashkey }}"/>
                <input type="text" name="captcha_1" maxlength="20" required lay-verify="required"
                       placeholder="请输入验证码" spellcheck="false" autocapitalize="off" autocorrect="off"
                       autocomplete="off" class="layui-input" id="captcha_1">
            </div>
            <div class="layui-form-mid" style="padding: 0 !important;">
                <a href="javascript:" title="点击一下刷新验证码"><img src="{{ captcha_img_url }}" alt="验证码" class="captcha"/></a>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-input-block">
                <button class="layui-btn" lay-submit lay-filter="formSubmit">登&nbsp;录</button>
                <button type="reset" class="layui-btn layui-btn-primary">重&nbsp;置</button>
            </div>
        </div>

    </form>
    去<a href="{% url 'users:join' %}">注册</a>
</div>

<script src="{% static 'js/ajax_csrf.js' %}"></script>

<script>
    let element, layer, form;
    layui.use(['element', 'layer', 'form',], function () {
        element = layui.element;
        element.init();
        layer = layui.layer;
        form = layui.form;
        form.on('submit(formSubmit)', function (data) {
            $.ajax({
                url: "{% url 'users:login' %}",
                type: "post",
                data: data.field,
                success: function (data) {
                    if (data["code"] === 200) {
                        layer.msg(data["msg"]);
                        setTimeout(function () {
                            window.location = data["next"];
                        }, 2 * 1000);
                    } else {
                        layer.msg(data["msg"]);
                        $.getJSON("{% url 'captcha-refresh' %}", function (result) {
                            $('.captcha').attr('src', result['image_url']);
                            $('#captcha_0').val(result['key'])
                        });
                    }
                }
            });
            return false;
        });
    });
    $('.captcha').click(function () {
        $.getJSON("{% url 'captcha-refresh' %}", function (result) {
            $('.captcha').attr('src', result['image_url']);
            $('#captcha_0').val(result['key'])
        });
    });
</script>
</body>
</html>

templates/users/update.html
{% load static %}
<!doctype html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>修改个人信息 - {{ request.user }}</title>
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
    <script src="{% static 'jquery/3.3.1/jquery.min.js' %}"></script>
    <script src="{% static 'js/ajax_csrf.js' %}"></script>
    <script src="{% static 'layui/layui.js' %}"></script>
</head>
<body>

<form action="{% url 'users:update' %}" method="post" class="layui-form">
    {% csrf_token %}
    <div class="layui-form-item">
        <label class="layui-form-label" for="id_nickname">昵称：</label>
        <div class="layui-input-inline">
            <input type="text" name="nickname" id="id_nickname" maxlength="15" required lay-verify="required"
                   placeholder="请输入昵称" value="{{ request.user.userinfo.nickname }}"
                   autocomplete="off" class="layui-input">
        </div>
        <div class="layui-form-mid layui-word-aux">&nbsp;</div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">性别：</label>
        <div class="layui-input-block">
            <label>
                <input type="radio" name="gender" value=1 title="男"{% if request.user.userinfo.gender %}
                       checked{% endif %}>
            </label>
            <label>
                <input type="radio" name="gender" value=0 title="女"{% if not request.user.userinfo.gender %}
                       checked{% endif %}>
            </label>
        </div>
    </div>

    <div class="layui-form-item">
        <div class="layui-input-block">
            <button class="layui-btn" lay-submit lay-filter="change">修&nbsp;改</button>
            <button type="reset" class="layui-btn layui-btn-primary">重&nbsp;置</button>
        </div>
    </div>
</form>

<form action="{% url 'users:password' %}" method="post" class="layui-form">
    {% csrf_token %}
    <div class="layui-form-item">
        <label class="layui-form-label" for="old_password">旧密码：</label>
        <div class="layui-input-inline">
            <input type="password" name="old_password" maxlength="15" required lay-verify="required"
                   placeholder="请输入旧密码" lay-type="pass"
                   autocomplete="off" class="layui-input" id="old_password">
        </div>
        <div class="layui-form-mid layui-word-aux">&nbsp;</div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label" for="new_password">新密码：</label>
        <div class="layui-input-inline">
            <input type="password" name="new_password" maxlength="15" required lay-verify="required|pass"
                   placeholder="请输入新密码" lay-type="pass"
                   autocomplete="off" class="layui-input" id="new_password">
        </div>
        <div class="layui-form-mid layui-word-aux">&nbsp;</div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label" for="password_1">确认密码：</label>
        <div class="layui-input-inline">
            <input type="password" maxlength="15" required lay-verify="required|confirmPass"
                   placeholder="请确认密码"
                   autocomplete="off" class="layui-input" id="password_1">
        </div>
        <div class="layui-form-mid layui-word-aux">&nbsp;</div>
    </div>
    <div class="layui-form-item">
        <div class="layui-input-block">
            <button class="layui-btn" lay-submit lay-filter="change">修改密码</button>
            <button type="reset" class="layui-btn layui-btn-primary">重&nbsp;置</button>
        </div>
    </div>
</form>

<script>
    let element, layer, form;
    layui.use(['element', 'layer', 'form',], function () {
        element = layui.element;
        element.init();
        layer = layui.layer;
        form = layui.form;
        form.on('submit(change)', function (data) {
            $.ajax({
                url: data.form.action,
                type: "post",
                data: data.field,
                success: function (data) {
                    if (data["code"] === 200) {
                        layer.msg(data["msg"]);
                        setTimeout(function () {
                            window.location = data["next"];
                        }, 2 * 1000);
                    } else {
                        layer.msg(data["msg"]);
                    }
                }
            });
            return false;
        });

        form.verify({
            pass: [/(.+){6,15}$/, '密码必须6到15位'],
            confirmPass: function (value) {
                if ($('input[name=new_password]').val() !== value)
                    return '两次密码输入不一致！';
            },
        });
    });
</script>
</body>
</html>